---

- name: Install Kubernetes packages
  include_tasks: pkg.yml

- name: Pass bridged IPv4 traffic to iptables’ chains
  shell: "sysctl net.bridge.bridge-nf-call-iptables=1"

- name: Override config file directory for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    dropin_dir: "/etc/systemd/system"

- name: Copy kubeadm conf to drop-in directory
  template: src=10-kubeadm.conf.j2 dest={{ dropin_dir }}/kubelet.service.d/10-kubeadm.conf

- name: Reload kubelet daemon
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
